import { autoUpdater } from 'electron-updater'
import { getSettings } from './store-node'
import { getLogger } from './util'

const log = getLogger('app-updater')

/**
 * Auto-update is wired to GitHub Releases of the fork repository.
 *
 * The publish target is configured in `electron-builder.yml` (provider: github).
 * `electron-updater` reads `app-update.yml` (generated by electron-builder)
 * at runtime, so we don't need to call `setFeedURL` here.
 *
 * If the user has disabled auto-update in settings, we skip wiring the
 * checker entirely and never reach out to any server.
 */
export class AppUpdater {
  constructor(onUpdateDownloaded: () => void) {
    log.transports.file.level = 'info'
    autoUpdater.logger = log

    autoUpdater.once('update-downloaded', (_event) => {
      onUpdateDownloaded()
    })

    const settings = getSettings()
    if (!settings.autoUpdate) {
      log.info('Auto-update disabled by user setting; skipping update checks')
      return
    }

    if (settings.betaUpdate) {
      autoUpdater.channel = 'beta'
      autoUpdater.allowDowngrade = false
    }

    this.tryUpdate()
    setInterval(
      () => {
        this.tryUpdate()
      },
      1000 * 60 * 60
    )
    log.info('Update timer started, checking every hour against GitHub Releases')
  }

  async tryUpdate() {
    try {
      return await autoUpdater.checkForUpdatesAndNotify()
    } catch (e) {
      log.error('auto_updater: check failed', e)
      return null
    }
  }
}
